name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x /home/runner/work/MishMashModpack/MishMashModpack/gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
