name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x /home/runner/work/MishMashModpack/MishMashModpack/gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Upload a Build Artifact As-Is
  # You may pin to the exact commit or the version.
  # uses: kittaakos/upload-artifact-as-is@68d1b5ae1264196668586be0246d797bfc8980e5
        uses: kittaakos/upload-artifact-as-is@v0
        with:
    # A file, directory or wildcard pattern that describes what to upload
         path: builds
