name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x /home/runner/work/MishMashModpack/MishMashModpack/gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with: 
         path: ./builds
